test

diff --git a/blenderupdate b/blenderupdate
--- a/blenderupdate
+++ b/blenderupdate
@@ -1,21 +1,22 @@
 #!/bin/bash
-#axel - light command line download accelerator
+#dependency: axel, wget.
 
-yay -Q | grep axel > /dev/null 2>&1 || echo "install axel - light command line download accelerator"
+nc=6 # number of connections
+# dependency check and blender download
+axel -V > /dev/null 2>&1 || echo "missing dependency: axel - light command line download accelerator"
+wget --version > /dev/null 2>&1 || echo "missing dependency: wget - the non-interactive network downloader."
 ls -l ~/blender/downloads/alpha/ > /dev/null 2>&1 || mkdir -p ~/blender/downloads/alpha/
 rm -r ~/blender/downloads/alpha/* > /dev/null 2>&1
 cd ~/blender/downloads/alpha/
-#var=$(wget -qO- https://builder.blender.org/download/daily/ | grep -o -G 'blender-.....-alpha+master.[0-9a-z]*-linux.x86_64-release.tar.xz' | awk 'NR==1')
 var=$(wget -qO- https://builder.blender.org/download/daily/ | grep -o -G 'blender-[^a-z]*-alpha+master.[0-9a-z]*-linux.x86_64-release.tar.xz' | awk 'NR==1')
-axel -n 10 https://builder.blender.org/download/daily/$var
-
-axel -n 10 https://builder.blender.org/download/daily/$var.sha256
+axel -n $nc https://builder.blender.org/download/daily/$var
+# sha256sum check
+axel -n $nc https://builder.blender.org/download/daily/$var.sha256
 echo $(cat $var.sha256) $var > $var.sha256
 sha256sum -c $var.sha256 || echo "sha256sum corrupt!" > log_sha
-
+# blender extract
 tar -xf ~/blender/downloads/alpha/*.tar.xz -C ~/blender/downloads/alpha
-#cp ~/blender/BlenderAlpha.desktop ~/.local/share/applications
-#sed -ie 's|Exec.*|Exec=~/blender/downloads/alpha/blender-*/blenderSSSSSSSSSSS %f |g' BlenderAlpha.desktop
+
 
 
 
